### ISSUE TITLE
FS Steam installation does not find settings

### ISSUE THREAD

**Issue by pmb2019** [dmenne/FS2020Control#1]
This is pmb from flightsim.to. I installed the new version 1.1.1 but still don't get any pdfs.

I use MSFS Steam, the Settings files (UserCfg.opt etc) are under 

C:\Users\Michael_Basler_2016\AppData\Roaming\Microsoft Flight Simulator

I use German Windows. Your program installs a link under

C:\Users\Michael_Basler_2016\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Menne Biomed

but I don't see where this link points to. I can't find the program itself.

**Comment by dmenne** [comment]
>> but I don't see where this link points to. I can't find the program itself.

I also don't understand why I cannot add a link on the desktop with ClickOnce (by Microsoft) during installation with VS 17. There was such an option in VS 2015/2019.

To start the program, try to type FS2020.... in Start. You can then choose to create a link in the Start menu or the task bar, but no on the desktop.

I do not have Steam, so I cannot easily help you. In case you get the program started and still nothing turns up, it would be nice to get your settings directory zipped.

**Comment by pmb2019** [comment]
I just had an idea to check the Windows Event Logger. Obviously, there is an error upon running. Here is the result:

Name der fehlerhaften Anwendung: FS2020Control.exe, Version: 1.1.1.0, Zeitstempel: 0x63cf722c
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.22621.1555, Zeitstempel: 0x686e4e74
Ausnahmecode: 0xc000041d
Fehleroffset: 0x001479d2
ID des fehlerhaften Prozesses: 0x0x5A8C
Startzeit der fehlerhaften Anwendung: 0x0x1D96CAC0CCDCFD5
Pfad der fehlerhaften Anwendung: C:\Users\Michael_Basler_2016\AppData\Local\Apps\2.0\3OEVBXP7.TOQ\3ATRWGMO.6T8\fs20..tion_3aa93aa4ee9ef9a1_0001.0001_cd7b4e204a3ffca0\FS2020Control.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: d1d1cc53-9cf2-4f98-8101-cb655ab81f94
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

This also shows me where the program is installed 

Which settings directory are you referring to for sending? The one named above

C:\Users\Michael_Basler_2016\AppData\Roaming\Microsoft Flight Simulator

is quite huge (flightplans, bush trips), but I could perhaps zip subdirectories of it.

BTW, I use Windows 11, if that matters. Some more info: The MSFS exe resides under 

C:\Program Files (x86)\Steam\steamapps\common\MicrosoftFlightSimulator

The simulator with /Official and /Community is under

D:\MSFS

I hope this helps. If you can't resolve it right now, perhaps someone else will find a solution at a point.

**Comment by dmenne** [comment]
Strange. This looks like a problem with the ClickOnce program, not with the wrong path to the settings found as I suspected first. An error in Kernelbase is a serious one, and should not happen at all. See, for example, [https://answers.microsoft.com/en-us/windows/forum/all/applications-fail-to-start-with-kernelbasedll/44a4c2ad-a43f-479b-b026-bcdc2ff01285](this ugly resolution), but better do not go that way, it looks scary. `sfc /scannow` from an admin console seems to be reasonably safe, but I give you only 10% chance that this will help.

**Comment by pmb2019** [comment]
I tried to locate the settings file according to your mail but failed. 

C:\Users\Michael_Basler_2016\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe

only holds one subdirectory, /LocalState, and further down the path info on the Just Flight PA28.

However, I recalled having read the Steam version stores controller settings in its own path. A search in the Steam path revelaed a directory

C:\Program Files (x86)\Steam\steamapps\common\MicrosoftFlightSimulator\Input

which holds a host of xml-files like the attached one. This might contain the information you are looking for.

[Saitek_Pro_Flight_Yoke.zip](https://github.com/dmenne/FS2020Control/files/11208808/Saitek_Pro_Flight_Yoke.zip)

**Comment by dmenne** [comment]
That looks perfect - too perfect. For example, it has the root element <DefaulftInput> which I had to fake to parse xml. Looks like MS realized the error too late for the non-steam version. I will try to simulate this on  my computer, and will send you a link to a private directory for testing later.

It's strange the Steam apps are in the 32-bit (x86) directory. Or maybe this is only the store for first time install? Then it is useless, because it does not reflect the current state.

Could you please make some change to your Saitek settings in FS2020 and check if the file (or the file date) changed?

Are you sure this is from FS2020? Or maybe the relics of some older version of FS? Last change was on 10.3.2023, which looks rather recent.

**Comment by dmenne** [comment]
Looks like Steam is really installed in that funny 32 Bit directory, but it can be moved

https://steamcommunity.com/app/1250410/discussions/1/2957166487940053315/

**Comment by pmb2019** [comment]
> Could you please make some change to your Saitek settings in FS2020 and check if the file (or the file date) changed?

Will do that tonight and check. From the date of the file I think it traces changes, but I'll recheck.

I find it strange, too, that Steam installs in the 32-Bit-path. Obviously this only refers to the Steam app itself which seemingly has to provide support for Legacy games (and perhaps Lagacy systems).  

BTW, while this is the default, the Steam path is not necessarily residing on C.  On my previous system I had the whole Steam directory with all games on another drive.

**Comment by dmenne** [comment]
I noted from other forum posts that the Steam path is often changed. I tried on the developer forum:

https://devsupport.flightsimulator.com/questions/16256/steam-installation-path-for-utilities.html

But anyway, I have now added a message box for your case, so that users do not have to dig up things in the event log.

**Comment by pmb2019** [comment]
I am pretty sure the path is saved in the registry, but don't ask me where.

If you have something to test later, I can certainly help with this.

**Comment by dmenne** [comment]
```
[HKEY_CURRENT_USER\Software\Valve\Steam]
"Language"="german"
"SteamInstaller"="SteamSetup.exe"
"SteamExe"="c:/program files (x86)/steam/steam.exe"

**Comment by pmb2019** [comment]
I think all further down the way relative to MSFS is fixed.

**Comment by dmenne** [comment]
Asobo has a strange sense of humour. In the non-steam installation, xml is not valid xml because the root element is missing, but in steam they have added it as:

``` 
<DefaulftInput Primary="1" PlatformAvailability="PC">
```

Defaultft? Some typo of an intern asked to "fix that xml"?

Anyway, I have a version which might work, but there is a missing link: in non-steam, I can give my Settings a name, e.g. "Prop" or "A320 neo", which appears as "FriendlyName" in Xml. Is that missing in the Steam edition? Can you supply a few more settings file for testing?

**Comment by pmb2019** [comment]
I've zipped and attached the complete directory.

Just a guess. The missing element could have been added by Steam, not Asobo. They might have corresponding xml guidelines as this is withing their realm. 

[Input.zip](https://github.com/dmenne/FS2020Control/files/11213283/Input.zip)

**Comment by pmb2019** [comment]
I just installed version  1.2 from flightsim.to, but it still doesn't work. Same result as before.

**Comment by dmenne** [comment]
Too bad. Simply crash to desktop? At least it should give a message now.

**Comment by dmenne** [comment]
Try to delete everything in ~\FS2020Keys

**Comment by pmb2019** [comment]
No message. It just creates the same three files and crashes as before. I could send you the files collected by the Windows error reporting, but I doubt you can extract anything meaningful out of them.

> Try to delete everything in ~\FS2020Keys

I did this already .

**Comment by dmenne** [comment]
Could you please check the event viewer: When I simulate the suspected case here, I get the following error message. Bold is the important part

Application: FS2020Control.exe
CoreCLR Version: 6.0.1523.11507
.NET Version: 6.0.15
Description: The process was terminated due to an unhandled exception.
Exception Info: FS2020Controls.FS2020Exception: **c:/program files (x86)/steam\steamapps\common\MicrosoftFlightSimulator\Input for Steam settings does not exist**
   at FS2020Controls.XmlToSqlite.CheckSteamInstallation() in C:\Users\Dieter\Documents\FS2020Control\FS2020Control\

**Comment by pmb2019** [comment]
I find several error reports in connection to several (trial) program starts. One of them is close to yours, though. Obviously it's still in search of the Store Version directory:

Application: FS2020Control.exe
CoreCLR Version: 6.0.1623.17311
.NET Version: 6.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Michael_Basler_2016\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\SystemAppData\wgs'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
.......

**Comment by dmenne** [comment]
Thanks, that helps. It really looks for the Store Version first, then for Steam, but it looks like the exception handling of "Store not found" has an issue (vulgo: bug).

**Comment by pmb2019** [comment]
I know it's not fun to maintain, but as a last resort, you could try to provide two versions, one for Store and one for Steam, perhaps?

**Comment by dmenne** [comment]
No, that will work, it was my error because my test simulation was not ok. Hopefully later today.

**Comment by pmb2019** [comment]
I tried 1.2.1 from flightsim.to but no joy yet. Removed anything in advance, but still doesn't work.

Application: FS2020Control.exe
CoreCLR Version: 6.0.1623.17311
.NET Version: 6.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Michael_Basler_2016\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\SystemAppData\wgs'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
...

**Comment by dmenne** [comment]
Could you please check if you have a directory

`C:\Users\Michael_Basler_2016\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe`

(which I expected should not be there in Steam, but ts.ts.... never expect)

and does it have subdirectories ?

**Comment by pmb2019** [comment]
Yes I do. Subdirectories are

C:\Users\Michael_Basler_2016\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalState\packages\justflight-aircraft-pa28-arrow-iii\work

This holds just 1 file "userinfo.txt" with (supposedly licensing) info on the JF PA28.

I agree, all that folder structure of MSFS is VERY confusing. It's spread like an octopus all over the system.

**Comment by dmenne** [comment]
Krr... Please give this one a try. I have turned around the testing sequence, but this might create other problems, because when both entries are there one never knows which one is used

https://menne-biomed.de/uni/SetupFS2020Control.zip

**Comment by pmb2019** [comment]
Wow - this one works. It installs and the app is launched. I don't have time to go through it right now because of RW work, but will try tonight. 

C:\Users\Michael_Basler_2016\Documents\FS2020Keys

initially, has only one file only, FS2020.sqlite. I guess it will be populated after properly executing the program.

Thanks a lot for your patience! I would much acknowledge your effort as I use several devices interchanging and often forget the more subtle key settings.

**Comment by dmenne** [comment]
uff.. Erst mal eine Pause.

**Comment by pmb2019** [comment]
Hi,

 

I am sorry, we are not yet there. This was my fault. The folder I told you contains the default controls profiles, not the user-adapted. I wanted to check this but forgot.

 

I made a search for the user-adapted profiles and this helped me:

 

https://forums.flightsimulator.com/t/where-can-i-save-the-control-profile-settings-file/347750

 

Hester40MT has it right. That's the place of the adapted user files. The MSFS identifier is always "1250410", but the path contains a free element. In my case it is

 

C:\Program Files (x86)\Steam\userdata\208453332\1250410\remote

 

I have zipped up the complete directory and attached it. To make things worse, these files don't have an xml extension, but it you open them they are xml (as far as I can judge this).

 

Sorry for this. I leave you with this info to decide if you want to pursue this any further.

 

Kind regards, Michael

 

_____________________

Michael Basler

Ernst-Bloch-Ring 30

D-07743 Jena, Germany

Tel.: 03641 368978

 ***@***.***> ***@***.***

 <http://www.michael-basler.net/> http://michael-basler.net

 

 

Von: Dieter Menne ***@***.***> 
Gesendet: Freitag, 14. April 2023 18:43
An: dmenne/FS2020Control ***@***.***>
Cc: pmb2019 ***@***.***>; Author ***@***.***>
Betreff: Re: [dmenne/FS2020Control] FS Steam installation does not find settings (Issue #1)

 

Closed #1 <https://github.com/dmenne/FS2020Control/issues/1>  as completed.

**Comment by dmenne** [comment]
Thanks for following this up.  I had feared something like this, because the directory looked too clean to be active. The issue has been reopened, and I will check once I got my own steam recovered.

You forgot to attach the zip directory.

**Comment by pmb2019** [comment]
Here is the zipped directory.

[remote.zip](https://github.com/dmenne/FS2020Control/files/11247630/remote.zip)

It was sent via mail but not transferred to GitHub.

Kind regards, Michael

**Comment by dmenne** [comment]
I will close this now, but feel free to reopen a new issue if there is a problem with Steam installations including/after 1.2.5
