### ISSUE TITLE
Action names don't match FS2020 

### ISSUE THREAD

**Issue by smitty97** [dmenne/FS2020Control#3]
I've found many action names dont match what they are in FS2020.. where are you pulling this text from?

For example "TRANSLATE COCKPIT VIEW FORWARD" is "Cockpit Camera Slide Front" in the app.  This makes rebuilding keybinds from the app's export difficult if we dont know exactly what to search for 

![image](https://github.com/user-attachments/assets/b613c19b-0c96-4f11-9455-df9ae4a124ba)

**Comment by dmenne** [comment]
I agree this is strange, but I fear I cannot do anything about it. The strings were extracted from a path which needs 2 lines here to display - check the code, this are "almost correct" XML file which are cached versions of online data and very volatile - names change on every update you make to you settings.

Sorry
